#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
COMPOSE_FILE="$ROOT_DIR/deploy/docker/openclaw-multi-instance.compose.yml"
INSTANCE_DIR="${OPENCLAW_MULTI_INSTANCE_DIR:-$HOME/.openclaw-instances}"
SOURCE_STATE_DIR="${OPENCLAW_SOURCE_STATE_DIR:-$HOME/.openclaw}"
BUILD_IMAGE=""
START_STACK=""
FORCE_CONFIG="${OPENCLAW_MULTI_INSTANCE_FORCE:-}"
REFRESH_AUTH="${OPENCLAW_MULTI_INSTANCE_REFRESH_AUTH:-}"

usage() {
  cat <<'EOF'
Usage: scripts/docker/setup-multi-instance.sh [options]

Creates local state/config/env files for:
  - llm-hub: central model proxy that owns the copied LLM auth store
  - pablo-0, pablo-1, pablo-2: Fluxer worker gateways that call llm-hub

Options:
  --build          Build OPENCLAW_IMAGE with the multi-instance compose file.
  --up             Start llm-hub, pablo-0, pablo-1, and pablo-2 after setup.
  --force          Rewrite generated openclaw.json files.
  --refresh-auth   Re-copy source auth/profile SQLite files into llm-hub.
  -h, --help       Show this help.

Useful env:
  OPENCLAW_MULTI_INSTANCE_DIR     Default: ~/.openclaw-instances
  OPENCLAW_SOURCE_STATE_DIR       Default: ~/.openclaw
  OPENCLAW_IMAGE                  Default: openclaw:fluxer-local
  OPENCLAW_LLM_MODEL_REF          Default: source agents.defaults.model.primary or openai/gpt-5.5
  OPENCLAW_LLM_GATEWAY_MODEL      Exposed model name served by llm-hub (default: upstream model id)
  FLUXER_BASE_URL                 Default: source channels.fluxer.baseUrl or http://192.168.240.117
  FLUXER_PABLO_0_BOT_TOKEN        pablo-0 Fluxer bot token
  FLUXER_PABLO_1_BOT_TOKEN        pablo-1 Fluxer bot token
  FLUXER_PABLO_2_BOT_TOKEN        pablo-2 Fluxer bot token
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --build)
      BUILD_IMAGE="1"
      ;;
    --up)
      START_STACK="1"
      ;;
    --force)
      FORCE_CONFIG="1"
      ;;
    --refresh-auth)
      REFRESH_AUTH="1"
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
  shift
done

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing dependency: $1" >&2
    exit 1
  fi
}

require_cmd node

export OPENCLAW_MULTI_INSTANCE_DIR="$INSTANCE_DIR"
export OPENCLAW_SOURCE_STATE_DIR="$SOURCE_STATE_DIR"
export OPENCLAW_MULTI_INSTANCE_FORCE="$FORCE_CONFIG"
export OPENCLAW_MULTI_INSTANCE_REFRESH_AUTH="$REFRESH_AUTH"

node <<'NODE'
const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

const instanceRoot = path.resolve(process.env.OPENCLAW_MULTI_INSTANCE_DIR);
const sourceStateDir = path.resolve(process.env.OPENCLAW_SOURCE_STATE_DIR);
const sourceConfigPath =
  process.env.OPENCLAW_SOURCE_CONFIG_PATH || path.join(sourceStateDir, "openclaw.json");
const forceConfig = process.env.OPENCLAW_MULTI_INSTANCE_FORCE === "1";
const refreshAuth = process.env.OPENCLAW_MULTI_INSTANCE_REFRESH_AUTH === "1";
const workerIds = (process.env.OPENCLAW_WORKER_IDS || "pablo-0 pablo-1 pablo-2")
  .split(/[,\s]+/u)
  .map((value) => value.trim())
  .filter(Boolean);

function readJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    return {};
  }
}

function writeJsonIfNeeded(file, value) {
  if (!forceConfig && fs.existsSync(file)) {
    return false;
  }
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, { mode: 0o600 });
  return true;
}

function parseEnvFile(file) {
  const result = {};
  if (!fs.existsSync(file)) {
    return result;
  }
  for (const rawLine of fs.readFileSync(file, "utf8").split(/\r?\n/u)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }
    const index = line.indexOf("=");
    if (index <= 0) {
      continue;
    }
    result[line.slice(0, index)] = line.slice(index + 1);
  }
  return result;
}

function writeEnvFile(file, values) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const lines = [
    "# Generated by scripts/docker/setup-multi-instance.sh",
    ...Object.entries(values)
      .filter(([, value]) => typeof value === "string" && value.length > 0)
      .map(([key, value]) => {
        if (/[\r\n]/u.test(value)) {
          throw new Error(`${key} cannot contain newlines`);
        }
        return `${key}=${value}`;
      }),
    "",
  ];
  fs.writeFileSync(file, lines.join("\n"), { mode: 0o600 });
}

function randomToken() {
  return crypto.randomBytes(32).toString("hex");
}

function ensureInstanceDirs(id) {
  const root = path.join(instanceRoot, id);
  for (const rel of [
    "state",
    "state/agents/main/agent",
    "state/agents/main/sessions",
    "workspace",
    "auth-profile-secrets",
  ]) {
    fs.mkdirSync(path.join(root, rel), { recursive: true });
  }
  return root;
}

function splitModelRef(raw, fallbackProvider = "openai") {
  const trimmed = String(raw || "").trim();
  if (!trimmed) {
    return { provider: fallbackProvider, modelId: "gpt-5.5" };
  }
  const slash = trimmed.indexOf("/");
  if (slash <= 0) {
    return { provider: fallbackProvider, modelId: trimmed };
  }
  return {
    provider: trimmed.slice(0, slash),
    modelId: trimmed.slice(slash + 1),
  };
}

function firstString(...values) {
  for (const value of values) {
    if (typeof value === "string" && value.trim()) {
      return value.trim();
    }
  }
  return "";
}

function resolveEnvSecretInput(value) {
  if (typeof value === "string") {
    const trimmed = value.trim();
    const envMatch = /^\$\{?([A-Z][A-Z0-9_]{0,127})\}?$/u.exec(trimmed);
    if (envMatch) {
      return process.env[envMatch[1]] || "";
    }
    return trimmed;
  }
  if (
    value &&
    typeof value === "object" &&
    value.source === "env" &&
    typeof value.id === "string"
  ) {
    return process.env[value.id] || "";
  }
  return "";
}

function envSecretRef(id) {
  return { source: "env", provider: "default", id };
}

function numberEnv(name, fallback) {
  const raw = process.env[name];
  if (!raw) {
    return fallback;
  }
  const parsed = Number.parseInt(raw, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

function copyFileIfPresent(source, target, overwrite) {
  if (!fs.existsSync(source)) {
    return false;
  }
  if (!overwrite && fs.existsSync(target)) {
    return false;
  }
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.copyFileSync(source, target);
  try {
    fs.chmodSync(target, fs.statSync(source).mode & 0o777);
  } catch {
    // Permissions are best-effort; Docker bind mounts may normalize them.
  }
  return true;
}

function copyDirIfTargetEmpty(source, target) {
  if (!fs.existsSync(source)) {
    return false;
  }
  if (fs.existsSync(target) && fs.readdirSync(target).length > 0) {
    return false;
  }
  fs.mkdirSync(target, { recursive: true });
  fs.cpSync(source, target, { recursive: true, force: false, errorOnExist: false });
  return true;
}

const sourceConfig = readJson(sourceConfigPath);
const sourceFluxer = sourceConfig?.channels?.fluxer || {};
const sourcePrimary =
  process.env.OPENCLAW_LLM_MODEL_REF ||
  sourceConfig?.agents?.defaults?.model?.primary ||
  Object.keys(sourceConfig?.agents?.defaults?.models || {})[0] ||
  "openai/gpt-5.5";
const explicitProvider = firstString(process.env.OPENCLAW_LLM_PROVIDER);
const modelParts = splitModelRef(sourcePrimary, explicitProvider || "openai");
const provider = explicitProvider || modelParts.provider;
const modelId = firstString(process.env.OPENCLAW_LLM_MODEL, modelParts.modelId, "gpt-5.5");
const gatewayModelId = firstString(process.env.OPENCLAW_LLM_GATEWAY_MODEL, modelId);
const hubModelRef = `${provider}/${modelId}`;
const workerProviderId = firstString(process.env.OPENCLAW_LLM_WORKER_PROVIDER, "openclaw-llm");
const workerModelRef = `${workerProviderId}/${gatewayModelId}`;
const fluxerBaseUrl = firstString(
  process.env.FLUXER_BASE_URL,
  sourceFluxer.baseUrl,
  "http://192.168.240.117",
);

for (const id of ["llm-hub", ...workerIds]) {
  ensureInstanceDirs(id);
}

const hubEnvPath = path.join(instanceRoot, "llm-hub", "instance.env");
const existingHubEnv = parseEnvFile(hubEnvPath);
const llmHubToken = firstString(process.env.LLM_HUB_TOKEN, existingHubEnv.LLM_HUB_TOKEN, randomToken());
writeEnvFile(hubEnvPath, {
  ...existingHubEnv,
  OPENCLAW_GATEWAY_TOKEN: firstString(existingHubEnv.OPENCLAW_GATEWAY_TOKEN, randomToken()),
  LLM_HUB_TOKEN: llmHubToken,
  TZ: firstString(process.env.OPENCLAW_TZ, existingHubEnv.TZ),
});

const hubConfig = {
  gateway: {
    mode: "local",
    auth: { mode: "token", token: envSecretRef("OPENCLAW_GATEWAY_TOKEN") },
    controlUi: { enabled: false },
    http: {
      endpoints: {
        modelProxy: {
          enabled: true,
          token: envSecretRef("LLM_HUB_TOKEN"),
          agentId: "main",
          defaultProvider: provider,
          defaultModel: gatewayModelId,
          routes: {
            [gatewayModelId]: hubModelRef,
          },
          allowedModels: [gatewayModelId],
          maxBodyBytes: numberEnv("OPENCLAW_LLM_HUB_MAX_BODY_BYTES", 2 * 1024 * 1024),
        },
      },
    },
  },
  agents: {
    defaults: {
      model: { primary: hubModelRef },
      models: { [hubModelRef]: {} },
    },
  },
};
writeJsonIfNeeded(path.join(instanceRoot, "llm-hub", "state", "openclaw.json"), hubConfig);

const sourceAgentDir = path.join(sourceStateDir, "agents", "main", "agent");
const hubAgentDir = path.join(instanceRoot, "llm-hub", "state", "agents", "main", "agent");
for (const suffix of ["", "-wal", "-shm"]) {
  copyFileIfPresent(
    path.join(sourceAgentDir, `openclaw-agent.sqlite${suffix}`),
    path.join(hubAgentDir, `openclaw-agent.sqlite${suffix}`),
    refreshAuth,
  );
}
copyFileIfPresent(
  path.join(sourceAgentDir, "auth-profiles.json"),
  path.join(hubAgentDir, "auth-profiles.json"),
  refreshAuth,
);

const sourceWorkspace = path.join(sourceStateDir, "workspace");
const sourceSessions = path.join(sourceStateDir, "agents", "main", "sessions");

function fluxerTokenForWorker(id, existingEnv) {
  const envName = `FLUXER_${id.toUpperCase().replace(/[^A-Z0-9]/gu, "_")}_BOT_TOKEN`;
  const legacyNamesById = {
    "pablo-0": ["FLUXER_MAIN_BOT_TOKEN", "FLUXER_BOT_TOKEN"],
    "pablo-1": ["FLUXER_AGENT_02_BOT_TOKEN"],
    "pablo-2": ["FLUXER_AGENT_03_BOT_TOKEN"],
  };
  const legacyValues = (legacyNamesById[id] || []).map((name) => process.env[name]);
  const sourceFallback =
    id === "pablo-0" || id === "main" ? resolveEnvSecretInput(sourceFluxer.token) : "";
  return firstString(
    process.env[envName],
    ...legacyValues,
    existingEnv.FLUXER_BOT_TOKEN,
    sourceFallback,
  );
}

function workerConfig(id, fluxerEnabled) {
  return {
    gateway: {
      mode: "local",
      auth: { mode: "token", token: envSecretRef("OPENCLAW_GATEWAY_TOKEN") },
      controlUi: { enabled: false },
    },
    models: {
      providers: {
        [workerProviderId]: {
          baseUrl: "http://llm-hub:18789/llm/v1",
          api: "openai-completions",
          auth: "api-key",
          apiKey: envSecretRef("LLM_HUB_TOKEN"),
          authHeader: true,
          models: [
            {
              id: gatewayModelId,
              name: `${gatewayModelId} via llm-hub`,
              api: "openai-completions",
              reasoning: false,
              input: ["text"],
              cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
              contextWindow: numberEnv("OPENCLAW_LLM_CONTEXT_WINDOW", 128000),
              contextTokens: numberEnv("OPENCLAW_LLM_CONTEXT_TOKENS", 96000),
              maxTokens: numberEnv("OPENCLAW_LLM_MAX_TOKENS", 32000),
              compat: {
                supportsUsageInStreaming: true,
                maxTokensField: "max_completion_tokens",
              },
            },
          ],
        },
      },
    },
    agents: {
      defaults: {
        model: { primary: workerModelRef },
        models: { [workerModelRef]: {} },
      },
    },
    messages: {
      groupChat: {
        unmentionedInbound: "room_event",
        visibleReplies: "message_tool",
        historyLimit: numberEnv("OPENCLAW_GROUP_HISTORY_LIMIT", 50),
      },
    },
    channels: {
      fluxer: {
        enabled: fluxerEnabled,
        baseUrl: fluxerBaseUrl,
        token: envSecretRef("FLUXER_BOT_TOKEN"),
        dmPolicy: "open",
        allowFrom: ["*"],
        groupPolicy: "open",
        requireMention: true,
        groups: { "*": { requireMention: true } },
      },
    },
  };
}

for (const id of workerIds) {
  const envPath = path.join(instanceRoot, id, "instance.env");
  const existingEnv = parseEnvFile(envPath);
  const fluxerToken = fluxerTokenForWorker(id, existingEnv);
  writeEnvFile(envPath, {
    ...existingEnv,
    OPENCLAW_GATEWAY_TOKEN: firstString(existingEnv.OPENCLAW_GATEWAY_TOKEN, randomToken()),
    LLM_HUB_TOKEN: llmHubToken,
    FLUXER_BOT_TOKEN: fluxerToken,
    TZ: firstString(process.env.OPENCLAW_TZ, existingEnv.TZ),
  });
  writeJsonIfNeeded(
    path.join(instanceRoot, id, "state", "openclaw.json"),
    workerConfig(id, Boolean(fluxerToken)),
  );
}

copyDirIfTargetEmpty(sourceWorkspace, path.join(instanceRoot, "pablo-0", "workspace"));
copyDirIfTargetEmpty(
  sourceSessions,
  path.join(instanceRoot, "pablo-0", "state", "agents", "main", "sessions"),
);

console.log(`Prepared OpenClaw multi-instance state in ${instanceRoot}`);
console.log(`LLM hub model: ${hubModelRef}`);
console.log(`LLM gateway model: ${gatewayModelId}`);
console.log(`Worker model: ${workerModelRef}`);
console.log(`Fluxer base URL: ${fluxerBaseUrl}`);
NODE

if [[ -n "$BUILD_IMAGE" || -n "$START_STACK" ]]; then
  require_cmd docker
  if ! docker compose version >/dev/null 2>&1; then
    echo "Docker Compose not available (try: docker compose version)" >&2
    exit 1
  fi
fi

if [[ -n "$BUILD_IMAGE" ]]; then
  docker compose -f "$COMPOSE_FILE" --profile extra-workers build
fi

if [[ -n "$START_STACK" ]]; then
  docker compose -f "$COMPOSE_FILE" --profile extra-workers up -d llm-hub pablo-0 pablo-1 pablo-2
fi

cat <<EOF

Next:
  docker compose -f "$COMPOSE_FILE" --profile extra-workers ps

To start only llm-hub + pablo-0 after reviewing configs:
  docker compose -f "$COMPOSE_FILE" up -d llm-hub pablo-0

To start the default three-worker stack:
  docker compose -f "$COMPOSE_FILE" --profile extra-workers up -d llm-hub pablo-0 pablo-1 pablo-2
EOF
